// Generated by https://quicktype.io

export interface EggGroup {
    id:              number;
    name:            string;
    names:           Name[];
    pokemon_species: PokemonSpecy[];
}

export interface Name {
    language: PokemonSpecy;
    name:     string;
}

export interface PokemonSpecy {
    name: string;
    url:  string;
}
